### ISSUE TITLE
factor/gmp-ecm/tinyecm.c fails to build when USE_AVX512F is not set

### ISSUE THREAD

**Issue by NyanCatTW1** [bbuhrow/yafu#20]
```
factor/gmp-ecm/tinyecm.c:5217:3: error: too few arguments to function ‘tecm_dispatch’
 5217 |   tecm_dispatch(n, f, target_bits, pran);
      |   ^~~~~~~~~~~~~
factor/gmp-ecm/tinyecm.c:4667:5: note: declared here
 4667 | int tecm_dispatch(mpz_t n, mpz_t f, int targetBits, int arbitrary, uint64_t* ploc_lcg)
      |     ^~~~~~~~~~~~~
```

Broken in commit c1ad4630e5589be31bc02cd62a6472c531f5718e
Line 5217 is only activated when USE_AVX512F is not set, which will explain how the commit got through the testing
